name: Publish version

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish package on npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Draft Github release with archive
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body: |
            ### :warning: Breaking changes

            ### :bulb: Features

            ### :beetle: Bug fixes

            ### :wrench: Technical
